# 2.2 Multiplying Matrix and Vectors
**dot product**   two matrix product **C=AB** , A must have the same number of columns as B has rows. If **A** is of shape m*n and **B** is of shape n*p, then **C** is of shape m*p
**C=AB** as $C_{i,j}=\sum_{k}A_{i,k}B_{k,j} $

In [1]:
import numpy as np

In [10]:
A = np.ones([2,4])
B = np.matrix([[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
C = np.dot(A,B)
print(A,'\nmatrix A shape:',A.shape,'\n',
      B,'\nmatrix B shape:',B.shape,'\n',
      C,'\nmatrix C shape:',C.shape,'\n')
C = np.zeros([A.shape[0],B.shape[1]])

for i in range(C.shape[0]):
    for j in range(C.shape[1]):
        tmp = 0
        for k in range(A.shape[1]):
            tmp += A[i,k]*B[k,j]
        C[i,j] = tmp
print(C)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] 
matrix A shape: (2, 4) 
 [[2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]] 
matrix B shape: (4, 3) 
 [[ 14.  14.  14.]
 [ 14.  14.  14.]] 
matrix C shape: (2, 3) 

[[ 14.  14.  14.]
 [ 14.  14.  14.]]


**matrix useful properites**

·**A(B+C)=AB+AC**

·**A(BC)=(AB)C**

·$x^Ty=y^Tx$

·**$(AB)^T=B^TA^T$**