# 2.3 Identity and Inverser Matrix

## Identity matrix 
*identity matrix* is a matrix **doesnot change any vector** when we multiply that vector by that matrix.  $I_n \in R^{n*n}$
$$\forall x\in R^n, I_nx=x$$
the identity marix is all of the entires along the main diagonal is 1, others are zero.

In [1]:
import numpy as np

In [7]:
I = np.identity(3,dtype=int)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Inverse Matrix
*Inverse Matrix* of a matrix **A** is denoted as $A^{-1}$, the property of inverse matrix is:
$$A^{-1}A=I_n$$
a simple exp :
$$Ax=b$$
$$A^{-1}Ax=A^{-1}b$$
$$I_nx=A^{-1}b$$
$$x=A^{-1}b$$
**but** the inverse matrix of A is not always exist, there are conditions for the existence of $A^{-1}$
So, in computer science we'll not actual use inverse matrix on a digital computer, just useful as a theoretical tool

In [32]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
print(A)

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]


In [33]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [34]:
print(A_inv.dot(A))

[[  1.00000000e+00   0.00000000e+00  -5.55111512e-17]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
